//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace nJupiter.DataAccess.DirectoryService.Adapters.WebService {
	using System.Net;
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="DirectoryServiceWebServiceSoap", Namespace="urn:services:dataaccess.directoryservice")]
	public class DirectoryServiceWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
		/// <remarks/>
		public DirectoryServiceWebService(string url, ICredentials credential) {
			this.Url = url;
			this.Credentials = credential;
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:services:dataaccess.directoryservice/GetDirectoryObjectById", RequestNamespace="urn:services:dataaccess.directoryservice", ResponseNamespace="urn:services:dataaccess.directoryservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("DirectoryObject", IsNullable=true)]
		public DirectoryObject GetDirectoryObjectById(string Id) {
			object[] results = this.Invoke("GetDirectoryObjectById", new object[] {
																					  Id});
			return ((DirectoryObject)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:services:dataaccess.directoryservice/GetDirectoryEntriesBySearchCriteria", RequestNamespace="urn:services:dataaccess.directoryservice", ResponseNamespace="urn:services:dataaccess.directoryservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlArrayAttribute("DirectoryObjects")]
		public DirectoryObject[] GetDirectoryEntriesBySearchCriteria([System.Xml.Serialization.XmlElementAttribute("SearchCriteria")] SearchCriteria[] SearchCriteria) {
			object[] results = this.Invoke("GetDirectoryEntriesBySearchCriteria", new object[] {
																								   SearchCriteria});
			return ((DirectoryObject[])(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:services:dataaccess.directoryservice/SaveDirectoryObject", RequestNamespace="urn:services:dataaccess.directoryservice", ResponseNamespace="urn:services:dataaccess.directoryservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public void SaveDirectoryObject(DirectoryObject DirectoryObject) {
			this.Invoke("SaveDirectoryObject", new object[] {
																DirectoryObject});
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:services:dataaccess.directoryservice/CreateDirectoryObjectInstance", RequestNamespace="urn:services:dataaccess.directoryservice", ResponseNamespace="urn:services:dataaccess.directoryservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("DirectoryObject", IsNullable=true)]
		public DirectoryObject CreateDirectoryObjectInstance() {
			object[] results = this.Invoke("CreateDirectoryObjectInstance", new object[0]);
			return ((DirectoryObject)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:services:dataaccess.directoryservice")]
	public class DirectoryObject {
        
		/// <remarks/>
		public string Id;
        
		/// <remarks/>
		public Property[] Properties;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:services:dataaccess.directoryservice")]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchCriteria))]
	public class Property {
        
		/// <remarks/>
		public string Name;
        
		/// <remarks/>
		public string Value;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:services:dataaccess.directoryservice")]
	public class SearchCriteria : Property {
		/// <remarks/>
		public bool Required;

	}
}